<!-- Blog/view/blog/index/add.phtml -->
<h3>Nouveau Pokemon</h3>

<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form); // <form method="POST">
?>

<div class="form-group">
    <?php echo $this->formRow($form->get('id_pokemon')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('name')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('description')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('type')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('evolution')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('image')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); // </form> ?>
