<?php

$title = 'Pokedex';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('pokedex', ['action' => 'add']) ?>">Ajouter un Pokemon</a>
</p>

<table class="table">
    <tr>
        <th>Nom</th>
        <th>Description</th>
        <th>Evolution</th>
    </tr>
    <?php foreach ($pokemons as $pokemon) : ?>
        <tr>
            <td><?= $this->escapeHtml($pokemon->name) ?></td>
            <td><?= $this->escapeHtml($pokemon->description) ?></td>
            <td><?= $this->escapeHtml($pokemon->evolved) ?></td>
            <td>
                <a href="<?= $this->url('pokedex', ['action' => 'edit', 'id' => $pokemon->id]) ?>">Modifier</a>
                <a href="<?= $this->url('pokedex', ['action' => 'delete', 'id' => $pokemon->id]) ?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>